spring:
  datasource:
    url: ${DATARA_DB_URL:jdbc:postgresql://localhost:5432/datara}
    username: ${DATARA_DB_USERNAME:datara}
    password: ${DATARA_DB_PASSWORD:datara}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DATARA_JPA_DDL_AUTO:validate}
  flyway:
    enabled: ${DATARA_FLYWAY_ENABLED:true}
